Add CI test specifically for doc-tests (and format file)
Co-authored-by: Sebastian Thiel <sebastian.thiel@icloud.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,8 +4,8 @@ on:
   push:
     branches:
       - main
-      - 'run-ci/**'
-      - '**/run-ci/**'
+      - "run-ci/**"
+      - "**/run-ci/**"
   pull_request:
     branches:
       - main
@@ -16,7 +16,7 @@ permissions:
 
 env:
   CARGO_TERM_COLOR: always
-  CLICOLOR: '1'
+  CLICOLOR: "1"
 
 jobs:
   msrv:
@@ -32,7 +32,7 @@ jobs:
 
     defaults:
       run:
-        shell: bash  # Use `bash` even in the Windows job.
+        shell: bash # Use `bash` even in the Windows job.
 
     steps:
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
@@ -104,7 +104,7 @@ jobs:
           )
           apt-get update
           apt-get install --no-install-recommends -y -- "${prerequisites[@]}"
-        shell: bash  # This step needs `bash`, and the default in container jobs is `sh`.
+        shell: bash # This step needs `bash`, and the default in container jobs is `sh`.
       - name: Verify that we are in an environment with limited dev tools
         run: |
           set -x
@@ -216,8 +216,26 @@ jobs:
           tool: nextest
       - name: test
         env:
-          GIX_TEST_IGNORE_ARCHIVES: '1'
+          GIX_TEST_IGNORE_ARCHIVES: "1"
         run: just ci-test
+
+  test-doc:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          persist-credentials: false
+      - name: Install Rust
+        run: |
+          rustup update stable
+          rustup default stable
+      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
+        with:
+          save-if: ${{ github.ref == 'refs/heads/main' }}
+      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
+      - name: Doctest
+        run: just doc-tests
 
   test-journey:
     runs-on: ubuntu-latest
@@ -247,9 +265,9 @@ jobs:
           - ubuntu-latest
           - ubuntu-24.04-arm
         include:
-          - test-args: ''
+          - test-args: ""
           - os: windows-11-arm
-            test-args: '--skip fuzzed_timeout --skip performance --skip speed'
+            test-args: "--skip fuzzed_timeout --skip performance --skip speed"
 
     runs-on: ${{ matrix.os }}
 
@@ -258,7 +276,7 @@ jobs:
         with:
           persist-credentials: false
       - name: Install Rust
-        shell: bash  # Use `bash` on all OSes, for `set -e` behavior.
+        shell: bash # Use `bash` on all OSes, for `set -e` behavior.
         run: |
           rustup update stable
           rustup default stable
@@ -273,7 +291,7 @@ jobs:
           tool: nextest
       - name: Test (nextest)
         env:
-          GIX_TEST_CREATE_ARCHIVES_EVEN_ON_CI: '1'
+          GIX_TEST_CREATE_ARCHIVES_EVEN_ON_CI: "1"
         # We deliberately let this step use different shells on different OSes, each the runner
         # default: `bash` on Ubuntu and macOS, but `pwsh` on Windows. `bash` on Windows runners
         # would use a modified ("Git Bash") environment that is in some ways nicer for our tests,
@@ -282,7 +300,7 @@ jobs:
         # `gix-testtools` is still able to run fixture scripts with the `bash` shell as intended.
         # `gix-error` is excluded because it gets compiled with the wrong feature toggles here.
         # It's tested individually.
-        run: |  # zizmor: ignore[template-injection]
+        run: | # zizmor: ignore[template-injection]
           cargo nextest run --workspace --no-fail-fast --exclude gix-error -- ${{ matrix.test-args }}
       - name: Check that tracked archives are up to date
         run: |
@@ -316,9 +334,9 @@ jobs:
           - windows-latest
           - windows-11-arm
         include:
-          - test-args: ''
+          - test-args: ""
           - os: windows-11-arm
-            test-args: '--skip fuzzed-timeout --skip performance --skip speed'
+            test-args: "--skip fuzzed-timeout --skip performance --skip speed"
 
     runs-on: ${{ matrix.os }}
 
@@ -327,7 +345,7 @@ jobs:
         with:
           persist-credentials: false
       - name: Install Rust
-        shell: bash  # Use `bash` (not `pwsh`), for `set -e` behavior.
+        shell: bash # Use `bash` (not `pwsh`), for `set -e` behavior.
         run: |
           rustup update stable
           rustup default stable
@@ -340,7 +358,7 @@ jobs:
       - name: Test (nextest)
         id: nextest
         env:
-          GIX_TEST_IGNORE_ARCHIVES: '1'
+          GIX_TEST_IGNORE_ARCHIVES: "1"
           TEST_ARGS: ${{ matrix.test-args }}
         run: |
           cargo nextest --profile=with-xml run --workspace --no-fail-fast --exclude gix-error -- `
@@ -370,7 +388,7 @@ jobs:
   test-32bit:
     strategy:
       matrix:
-        container-architecture: [ i386, arm32v7 ]
+        container-architecture: [i386, arm32v7]
         include:
           - container-architecture: i386
             runner-architecture: amd64
@@ -405,7 +423,7 @@ jobs:
           dpkg --add-architecture "$RUNNER_ARCHITECTURE"
           apt-get update
           apt-get install --no-install-recommends -y -- "${prerequisites[@]}"
-        shell: bash  # This step needs `bash`, and the default in container jobs is `sh`.
+        shell: bash # This step needs `bash`, and the default in container jobs is `sh`.
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
           persist-credentials: false
@@ -428,7 +446,7 @@ jobs:
         run: git config --system gitoxide.imaginary.arbitraryVariable arbitraryValue
       - name: Test (nextest)
         env:
-          GIX_TEST_IGNORE_ARCHIVES: '1'
+          GIX_TEST_IGNORE_ARCHIVES: "1"
         run: cargo nextest run --workspace --no-fail-fast --exclude gix-error
 
   test-32bit-windows-size-doc:
@@ -442,7 +460,7 @@ jobs:
         with:
           persist-credentials: false
       - name: Install Rust
-        shell: bash  # Use `bash` (not `pwsh`), for `$` expansion and `set -e` behavior.
+        shell: bash # Use `bash` (not `pwsh`), for `$` expansion and `set -e` behavior.
         run: |
           rustup update stable
           rustup default stable
@@ -526,7 +544,7 @@ jobs:
 
     strategy:
       matrix:
-        target: [ wasm32-unknown-unknown, wasm32-wasip1, wasm32-wasip2 ]
+        target: [wasm32-unknown-unknown, wasm32-wasip1, wasm32-wasip2]
 
     env:
       TARGET: ${{ matrix.target }}
@@ -543,7 +561,7 @@ jobs:
       - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
         with:
           save-if: ${{ github.ref == 'refs/heads/main' }}
-      - name: 'WASI only: crates without feature toggle'
+      - name: "WASI only: crates without feature toggle"
         if: startsWith(matrix.target, 'wasm32-wasi')
         run: |
           set -x
@@ -616,7 +634,7 @@ jobs:
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
           persist-credentials: false
-          sparse-checkout: '.github/workflows'
+          sparse-checkout: ".github/workflows"
       - name: List workflows to be scanned
         run: |
           shopt -s extglob
@@ -647,7 +665,7 @@ jobs:
 
     defaults:
       run:
-        shell: bash  # Without this, the shell here is `bash` but without `-o pipefail`.
+        shell: bash # Without this, the shell here is `bash` but without `-o pipefail`.
 
     steps:
       - name: Find this workflow
@@ -680,6 +698,7 @@ jobs:
       - msrv-badge
       - pure-rust-build
       - test
+      - test-doc
       - test-journey
       - test-fast
       - test-fixtures-windows
@@ -690,7 +709,7 @@ jobs:
       - check-no-persist-credentials
       - check-blocking
 
-    if: always()  # Always run even if dependencies fail.
+    if: always() # Always run even if dependencies fail.
 
     runs-on: ubuntu-slim
 
